version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/commerce_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: John0524@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"


  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql


    environment:
      MYSQL_ROOT_PASSWORD: John0524@
      MYSQL_DATABASE: commerce_service


volumes:
  db_data: